origins = ["Sebille",
           "Lohse",
           "Ifan Ben-Mezd",
           "Beast",
           "The Red Prince",
           "Fane"]

races = ["Dwarf",
         "Elf",
         "Human",
         "Lizard",
         "Undead Dwarf",
         "Undead Elf",
         "Undead Human",
         "Undead Lizard"]

classes = ["Wizard",
           "Wayfarer",
           "Shadowblade",
           "Rogue",
           "Ranger",
           "Knight",
           "Inquisitor",
           "Fighter",
           "Enchanter",
           "Cleric",
           "Battlemage",
           "Witch",
           "Conjurer",
           "Metamorph"]

genders = ["Female", "Male"]

attributes = ["Strength",
              "Finesse",
              "Intelligence",
              "Constitution",
              "Wits",
              "Memory"]

startingskills = {
    "Aerothurge": ["Favourable Wind",
                   "Blinding Radiance",
                   "Electric Discharge",
                   "Shocking Touch"],
    "Geomancer": ["Contamination",
                  "Fortify",
                  "Fossil Strike",
                  "Poison Dart"],
    "Huntsman": ["Elemental Arrowheads",
                 "First Aid",
                 "Ricochet",
                 "Pin Down"],
    "Hydrosophist": ["Armour of Frost",
                     "Rain",
                     "Restoration",
                     "Hail Strike"],
    "Necromancer": ["Blood Sucker",
                    "Decaying Touch",
                    "Mosquito Swarm",
                    "Raise Bloated Corpse"],
    "Polymorph": ["Bull Horns",
                  "Chicken Claw",
                  "Tentacle Lash",
                  "Chameleon Cloak"],
    "Pyrokinetic": ["Haste",
                    "Ignition",
                    "Peace of Mind",
                    "Searing Daggers"],
    "Scoundrel": ["Adrenaline",
                  "Backlash",
                  "Chloroform",
                  "Throwing Knife"],
    "Summoning": ["Conjure Incarnate",
                  "Dimensional Bolt",
                  "Elemental Totem",
                  "Farsight Infusion"],
    "Warfare": ["Battering Ram",
                "Battle Stomp",
                "Bouncing Shield",
                "Crippling Blow"]
    }

weapons = ["Single-Handed",
           "Two-Handed",
           "Ranged",
           "Dual Wielding"]

defence = ["Retribution",
           "Leadership",
           "Perserverance"]

civilskills = ["Bartering",
               "Lucky Charm",
               "Persuasion",
               "Loremaster",
               "Telekinesis",
               "Sneaking",
               "Thievery"]

talents = ["Ambidextrous",
           "Arrow Recovery",
           "Comeback Kid",
           "Demon",
           "Duck Duck Goose",
           "Elemental Affinity",
           "Elemental Ranger",
           "Escapist",
           "Executioner",
           "Far Out Man",
           "Five Star Diner",
           "Glass Cannon",
           "Guerilla",
           "Hothead",
           "Ice King",
           "Leech",
           "Living Armor",
           "Lone Wolf",
           "Mnemonic",
           "Morning Person",
           "Opportunist",
           "Parry Master",
           "The Pawn",
           "Picture of Health",
           "Slingshot",
           "Stench",
           "Pet Pal",
           "Torturer",
           "Unstable",
           "Walk It Off",
           "What A Rush"]

tags = ["Barbarian",
        "Jester",
        "Mystic",
        "Noble",
        "Outlaw",
        "Scholar",
        "Soldier"]

instruments = ["Bansuri", "Tambura", "Oud", "Cello"]
